# Generated by Django 4.2.7 on 2023-12-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Slag'),
        ),
    ]
